### ISSUE TITLE
Kanban board: Setup Project

### ISSUE THREAD

**Issue by usorfaitheloho** [usorfaitheloho/space-travellers#25]
For this capstone, we are a team of 3 developers.

@usorfaitheloho 
@bushmusi 
@samiullahbahadur 

Here is the link to the [kanban board](https://github.com/usorfaitheloho/space-travellers/projects/1)

**Comment by keroloussamy** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say
Congratulations! 🎉 


![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)




Cheers and Happy coding!👏👏👏

**Comment by usorfaitheloho** [comment]
Hello @keroloussamy ,

Thanks for your review 😄
